name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install test packages and coverage if not already in requirements.txt
        pip install pytest pytest-html coverage

    - name: Run Tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Generate Coverage Report
      run: |
        coverage run -m pytest
        coverage report
